### ISSUE TITLE
Compatibility with Dolibarr 4.0.2

### ISSUE THREAD

**Issue by romainbjl** [maximejay/dolibarr_alpiroc#1]
Hello, will it be possible for you to make hat great module compatible with Dolibarr 4.0.2 ?
I managed to add it to my current configuration but when I want to configure it I have this error message "Include of main fails"
Thanks for your feedback

**Comment by maximejay** [comment]
Hello,

Did you download the module from the Dolistore or from Github ?

After the release 4.0 I updated the module to fix some issues. I didn't 
try with the 4.0.2. The release on the Dolistore should be OK. But from 
Github, the release tagged 1.2.6 didn't work. I created a new one today 
tagged 1.2.7 which should work with Dolibarr 4.0.0.

Could you told me if it's a problem with the version of the module you 
are using or with the minor 4.0.2 version of Dolibarr.

Thank you for reporting this issue

Best regards
Maxime Jay-Allemand

**Comment by romainbjl** [comment]
Hello, 

thanks for you feedback.
I just disabled the module, removed it and added it again (downloaded from github) and I've got the same issue. ("Include of main fails")
In the module configuration menu, the module is still tagged 1.2.6. Tell me if some logs files can help you.
Thanks,
Romainbjl

**Comment by maximejay** [comment]
Ok thanks,

last things, where did you install the module ? I use to install (just 
copy the directory alpiroc) it in /dolibarr/htdocs/ (at least I know it 
worked here).

You could check the first lines (l 40 to 44) of this file : 
/var/www/html/dolibarr-3.8.0/htdocs/alpiroc/admin/alpiroc_setupapage.php

The error probably comes from here: the php script main.inc.php is not 
found... there is 4 successive test to find this script. So that could 
failed if the module has been installed at the wrong place or if 
main.inc.php has been renamed from the 4.0.0 version...

**Comment by romainbjl** [comment]
Ok I tried again adding the module in /var/www/dolibarr/htdocs/ and it worked.

I don't remebember where I read to add the module in /var/www/dolibarr/htdocs/custom. I didn't thought it was the wrong path because alpiroc appeared in the modules list.

Anyway thanks for your help, your module is exactly what I needed !

Best regards
Romainbjl

**Comment by maximejay** [comment]
Perfect !

The module should works even you install it in custom (it's a Dolibarr 
notification). I will correct it, but later... !
